services:
  app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    container_name: activity_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - .env.docker:/var/www/html/.env
    ports:
      - "4001:9000"
    depends_on:
      - postgres
    networks:
      - activity_network
    command: >
      bash -c "composer install && npm install && npm run build && php artisan key:generate && php artisan migrate  && php-fpm"

  postgres:
    image: postgres:13
    container_name: activity_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "4002:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - activity_network

  nginx:
    image: nginx:latest
    container_name: activity_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:80"
    depends_on:
      - app
    networks:
      - activity_network

  redis:
    image: redis:alpine
    container_name: activity_redis
    ports:
      - "4003:6379"
    networks:
      - activity_network

networks:
  activity_network: