services:
  app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    image: activity-image:latest
    container_name: activity_app
    restart: always
    volumes:
      - ./build:/var/www/html/public/build
      - .env.docker:/var/www/html/.env
    ports:
      - "4001:9000"
    depends_on:
      - postgres
    networks:
      - activity_network
    command: >
      bash -c "php artisan migrate --force --no-interaction && php-fpm"

  postgres:
    image: postgres:13
    container_name: activity_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "4002:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - activity_network
  nginx:
    image: nginx:latest
    container_name: activity_nginx
    restart: always
    volumes:
      - ./build:/var/www/html/public/build
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - activity_network

  redis:
    image: redis:alpine
    restart: always
    container_name: activity_redis
    ports:
      - "4003:6379"
    networks:
      - activity_network

networks:
  activity_network: